export type ResourceKey = string;

export type ResourceConfig = {
  key: ResourceKey;
  title: string;
  description: string;
  delegate: string;
  route: string;
  api: string;
  searchFields: string[];
  columns: { key: string; label: string }[];
  financeOnly?: boolean;
};

function resource(config: ResourceConfig) {
  return config;
}

export const resources: Record<string, ResourceConfig> = {
  users: resource({
    key: "users",
    title: "المستخدمين",
    description: "إدارة مستخدمي النظام والصلاحيات ونطاق المدن والمشرفين.",
    delegate: "user",
    route: "/users",
    api: "/api/users",
    searchFields: ["name", "email", "role", "status"],
    columns: [
      { key: "name", label: "الاسم" },
      { key: "email", label: "الإيميل" },
      { key: "role", label: "الصلاحية" },
      { key: "isActive", label: "نشط" },
      { key: "status", label: "الحالة" },
    ],
  }),
  cities: resource({
    key: "cities",
    title: "المدن",
    description: "إدارة المدن وربطها بالمشاريع والمناديب والمشرفين.",
    delegate: "city",
    route: "/cities",
    api: "/api/cities",
    searchFields: ["nameAr", "nameEn", "status"],
    columns: [
      { key: "nameAr", label: "المدينة" },
      { key: "nameEn", label: "City" },
      { key: "status", label: "الحالة" },
      { key: "updatedAt", label: "آخر تحديث" },
    ],
  }),
  projects: resource({
    key: "projects",
    title: "المشاريع",
    description: "إدارة المشاريع والتطبيقات المرتبطة بها.",
    delegate: "project",
    route: "/projects",
    api: "/api/projects",
    searchFields: ["name", "appName", "cityId", "status"],
    columns: [
      { key: "name", label: "المشروع" },
      { key: "appName", label: "التطبيق" },
      { key: "cityId", label: "المدينة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  supervisors: resource({
    key: "supervisors",
    title: "المشرفين",
    description: "بيانات المشرفين وربطهم بالمدن والمناديب والمهام.",
    delegate: "supervisor",
    route: "/supervisors",
    api: "/api/supervisors",
    searchFields: ["name", "phone", "email", "cityId", "status"],
    columns: [
      { key: "name", label: "المشرف" },
      { key: "phone", label: "الجوال" },
      { key: "email", label: "الإيميل" },
      { key: "cityId", label: "المدينة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  drivers: resource({
    key: "drivers",
    title: "المناديب",
    description: "ملف المناديب وربطه بالمدينة والمشروع والمشرف والسيارة والحساب.",
    delegate: "driver",
    route: "/drivers",
    api: "/api/drivers",
    searchFields: ["internalCode", "driverCode", "name", "actualName", "phone", "mobile", "nationalId", "status"],
    columns: [
      { key: "internalCode", label: "كود المندوب" },
      { key: "name", label: "الاسم" },
      { key: "phone", label: "الجوال" },
      { key: "cityId", label: "المدينة" },
      { key: "projectId", label: "المشروع" },
      { key: "supervisorId", label: "المشرف" },
      { key: "status", label: "الحالة" },
    ],
  }),
  vehicles: resource({
    key: "vehicles",
    title: "السيارات",
    description: "إدارة السيارات واللوحات والتأجير والحالة والمندوب الحالي.",
    delegate: "vehicle",
    route: "/vehicles",
    api: "/api/vehicles",
    searchFields: ["vehicleCode", "plateAr", "plateArabic", "plateEn", "plateEnglish", "model", "rentalCompany", "status"],
    columns: [
      { key: "plateAr", label: "اللوحة عربي" },
      { key: "plateEn", label: "اللوحة إنجليزي" },
      { key: "model", label: "الموديل" },
      { key: "rentalCompany", label: "شركة التأجير" },
      { key: "monthlyRent", label: "الإيجار الشهري" },
      { key: "status", label: "الحالة" },
    ],
  }),
  applications: resource({
    key: "applications",
    title: "مركز التطبيقات",
    description: "إدارة التطبيقات الرسمية مثل Keeta وHungerStation وTalabat.",
    delegate: "application",
    route: "/applications",
    api: "/api/applications",
    searchFields: ["code", "name", "status"],
    columns: [
      { key: "code", label: "كود التطبيق" },
      { key: "name", label: "اسم التطبيق" },
      { key: "description", label: "الوصف" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "application-projects": resource({
    key: "application-projects",
    title: "مشاريع التطبيقات",
    description: "مشاريع كل تطبيق داخل المدن.",
    delegate: "applicationProject",
    route: "/applications",
    api: "/api/application-projects",
    searchFields: ["code", "name", "applicationId", "cityId", "status"],
    columns: [
      { key: "code", label: "كود المشروع" },
      { key: "name", label: "اسم المشروع" },
      { key: "applicationId", label: "التطبيق" },
      { key: "cityId", label: "المدينة" },
      { key: "monthlyTarget", label: "التارجت الشهري" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "daily-reports": resource({
    key: "daily-reports",
    title: "التقارير اليومية",
    description: "تقارير الأداء اليومية للمناديب حسب التاريخ والمشروع.",
    delegate: "dailyReport",
    route: "/daily-reports",
    api: "/api/daily-reports",
    searchFields: ["month", "appName", "driverId", "cityId", "projectId"],
    columns: [
      { key: "reportDate", label: "التاريخ" },
      { key: "month", label: "الشهر" },
      { key: "driverId", label: "المندوب" },
      { key: "appName", label: "التطبيق" },
      { key: "orders", label: "الطلبات" },
      { key: "workingHours", label: "ساعات العمل" },
      { key: "onTimeRate", label: "On-Time" },
    ],
  }),
  advances: resource({
    key: "advances",
    title: "السلف",
    description: "سلف المناديب وحالتها وتسميعها في المسير.",
    delegate: "advance",
    route: "/advances",
    api: "/api/advances",
    searchFields: ["driverId", "reason", "deductionMonth", "status"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "amount", label: "المبلغ" },
      { key: "remainingAmount", label: "المتبقي" },
      { key: "deductionMonth", label: "شهر الخصم" },
      { key: "status", label: "الحالة" },
    ],
    financeOnly: true,
  }),
  deductions: resource({
    key: "deductions",
    title: "الخصومات",
    description: "خصومات المناديب اليدوية والتشغيلية المرتبطة بالمسير.",
    delegate: "deduction",
    route: "/deductions",
    api: "/api/deductions",
    searchFields: ["driverId", "type", "month", "status", "notes"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "type", label: "النوع" },
      { key: "amount", label: "المبلغ" },
      { key: "month", label: "الشهر" },
      { key: "status", label: "الحالة" },
    ],
    financeOnly: true,
  }),
  violations: resource({
    key: "violations",
    title: "المخالفات",
    description: "مخالفات المناديب والسيارات وربطها بالمسير بعد الاعتماد.",
    delegate: "violation",
    route: "/violations",
    api: "/api/violations",
    searchFields: ["driverId", "vehicleId", "type", "status", "notes"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "vehicleId", label: "السيارة" },
      { key: "type", label: "النوع" },
      { key: "amount", label: "المبلغ" },
      { key: "occurredAt", label: "التاريخ" },
      { key: "status", label: "الحالة" },
    ],
  }),
  payroll: resource({
    key: "payroll",
    title: "مسير الرواتب",
    description: "مسير رواتب المناديب. مستحق كيتا يظهر كإيراد شركة ولا يدخل في راتب المندوب.",
    delegate: "payroll",
    route: "/payroll",
    api: "/api/payroll",
    searchFields: ["driverId", "projectId", "month", "status"],
    columns: [
      { key: "month", label: "الشهر" },
      { key: "driverId", label: "المندوب" },
      { key: "projectId", label: "المشروع" },
      { key: "basicSalary", label: "الراتب الأساسي" },
      { key: "bonus", label: "الحوافز" },
      { key: "deductions", label: "الخصومات" },
      { key: "netSalary", label: "صافي راتب المندوب" },
      { key: "status", label: "الحالة" },
    ],
    financeOnly: true,
  }),
  tasks: resource({
    key: "tasks",
    title: "مهام المشرفين",
    description: "مهام التشغيل المرتبطة بالمشرفين والتنبيهات والمناديب.",
    delegate: "task",
    route: "/supervisor-tasks",
    api: "/api/supervisor-tasks",
    searchFields: ["title", "description", "status", "priority", "supervisorId", "driverId"],
    columns: [
      { key: "title", label: "المهمة" },
      { key: "supervisorId", label: "المشرف" },
      { key: "driverId", label: "المندوب" },
      { key: "priority", label: "الأولوية" },
      { key: "status", label: "الحالة" },
      { key: "dueDate", label: "موعد المتابعة" },
    ],
  }),
  notifications: resource({
    key: "notifications",
    title: "الإشعارات والتنبيهات",
    description: "تنبيهات حقيقية مرتبطة بالمندوب أو المدينة أو المشروع.",
    delegate: "notification",
    route: "/notifications",
    api: "/api/notifications",
    searchFields: ["title", "body", "severity", "status", "driverId", "entityType"],
    columns: [
      { key: "title", label: "التنبيه" },
      { key: "driverId", label: "المندوب" },
      { key: "severity", label: "الشدة" },
      { key: "status", label: "الحالة" },
      { key: "createdAt", label: "تاريخ الإنشاء" },
    ],
  }),
  interviews: resource({
    key: "interviews",
    title: "المقابلات",
    description: "إدارة مقابلات المرشحين وتحويل المقبولين إلى مناديب.",
    delegate: "interview",
    route: "/interviews",
    api: "/api/interviews",
    searchFields: ["candidateName", "phone", "status"],
    columns: [
      { key: "candidateName", label: "المرشح" },
      { key: "phone", label: "الجوال" },
      { key: "scheduledAt", label: "موعد المقابلة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "driver-documents": resource({
    key: "driver-documents",
    title: "مستندات المناديب",
    description: "مستندات المناديب وحالة الصلاحية والتنبيهات.",
    delegate: "driverDocument",
    route: "/rider-documents",
    api: "/api/driver-documents",
    searchFields: ["driverId", "type", "documentType", "status", "verificationStatus"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "type", label: "نوع المستند" },
      { key: "expiryDate", label: "تاريخ الانتهاء" },
      { key: "verificationStatus", label: "التحقق" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "driver-contracts": resource({
    key: "driver-contracts",
    title: "العقود والكفالة",
    description: "عقود المناديب والكفالة وأجير والفريلانسر.",
    delegate: "driverContract",
    route: "/contracts-sponsorship",
    api: "/api/driver-contracts",
    searchFields: ["driverId", "contractType", "sponsor", "status"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "contractType", label: "نوع العقد" },
      { key: "sponsor", label: "الكفيل" },
      { key: "endDate", label: "تاريخ الانتهاء" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "driver-housing": resource({
    key: "driver-housing",
    title: "سكن المناديب",
    description: "سكن المناديب وتكلفته وربطه بالخصومات إن لزم.",
    delegate: "driverHousing",
    route: "/rider-housing",
    api: "/api/driver-housing",
    searchFields: ["driverId", "housingType", "accommodationType", "location", "status"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "housingType", label: "نوع السكن" },
      { key: "location", label: "الموقع" },
      { key: "monthlyCost", label: "التكلفة الشهرية" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "driver-warnings": resource({
    key: "driver-warnings",
    title: "إنذارات المناديب",
    description: "إنذارات الأداء والحضور والمخالفات والمستندات.",
    delegate: "driverWarning",
    route: "/rider-warnings",
    api: "/api/driver-warnings",
    searchFields: ["driverId", "type", "severity", "status", "notes"],
    columns: [
      { key: "driverId", label: "المندوب" },
      { key: "type", label: "النوع" },
      { key: "severity", label: "الشدة" },
      { key: "issuedAt", label: "تاريخ الإنذار" },
      { key: "status", label: "الحالة" },
    ],
  }),
  attendance: resource({
    key: "attendance",
    title: "الحضور والانصراف",
    description: "تسجيل حضور وانصراف المناديب والمشرفين مع الصور عند توفرها.",
    delegate: "attendanceRecord",
    route: "/attendance",
    api: "/api/attendance",
    searchFields: ["driverId", "supervisorId", "personType", "status", "notes"],
    columns: [
      { key: "personType", label: "النوع" },
      { key: "driverId", label: "المندوب" },
      { key: "supervisorId", label: "المشرف" },
      { key: "workDate", label: "التاريخ" },
      { key: "workingHours", label: "الساعات" },
      { key: "status", label: "الحالة" },
    ],
  }),
  shifts: resource({
    key: "shifts",
    title: "الشفتات",
    description: "إدارة شفتات المناديب.",
    delegate: "shift",
    route: "/shifts",
    api: "/api/shifts",
    searchFields: ["name", "driverId", "cityId", "status"],
    columns: [
      { key: "name", label: "اسم الشفت" },
      { key: "driverId", label: "المندوب" },
      { key: "startTime", label: "البداية" },
      { key: "endTime", label: "النهاية" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "uploaded-reports": resource({
    key: "uploaded-reports",
    title: "تقارير مرفوعة",
    description: "سجل الملفات والتقارير المرفوعة للنظام.",
    delegate: "uploadedReport",
    route: "/uploaded-reports",
    api: "/api/uploaded-reports",
    searchFields: ["fileName", "importType", "appName", "month", "status"],
    columns: [
      { key: "fileName", label: "اسم الملف" },
      { key: "importType", label: "نوع الاستيراد" },
      { key: "appName", label: "التطبيق" },
      { key: "month", label: "الشهر" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "app-account-movements": resource({
    key: "app-account-movements",
    title: "حركة الحسابات",
    description: "حركة ربط ونقل حسابات التطبيقات.",
    delegate: "appAccountMovement",
    route: "/account-movement",
    api: "/api/app-account-movements",
    searchFields: ["accountId", "appName", "movementType", "status"],
    columns: [
      { key: "accountId", label: "الحساب" },
      { key: "appName", label: "التطبيق" },
      { key: "movementType", label: "نوع الحركة" },
      { key: "movementDate", label: "التاريخ" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "city-targets": resource({
    key: "city-targets",
    title: "تارجت المدن",
    description: "أهداف شهرية لكل مدينة ومشروع.",
    delegate: "cityTarget",
    route: "/city-targets",
    api: "/api/city-targets",
    searchFields: ["cityId", "projectId", "appName", "month", "status"],
    columns: [
      { key: "cityId", label: "المدينة" },
      { key: "projectId", label: "المشروع" },
      { key: "appName", label: "التطبيق" },
      { key: "monthlyTarget", label: "التارجت الشهري" },
      { key: "month", label: "الشهر" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "import-batches": resource({
    key: "import-batches",
    title: "عمليات الاستيراد",
    description: "سجل عمليات الاستيراد العامة.",
    delegate: "importBatch",
    route: "/imports",
    api: "/api/import-batches",
    searchFields: ["fileName", "importType", "appName", "month", "status"],
    columns: [
      { key: "fileName", label: "اسم الملف" },
      { key: "importType", label: "نوع الاستيراد" },
      { key: "rowsFound", label: "الصفوف" },
      { key: "rowsImported", label: "المستوردة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "audit-logs": resource({
    key: "audit-logs",
    title: "سجل العمليات",
    description: "سجل العمليات الحساسة والتعديلات.",
    delegate: "auditLog",
    route: "/audit-log",
    api: "/api/audit-logs",
    searchFields: ["user", "action", "entityType", "entityId"],
    columns: [
      { key: "user", label: "المستخدم" },
      { key: "action", label: "الإجراء" },
      { key: "entityType", label: "الكيان" },
      { key: "entityId", label: "رقم السجل" },
      { key: "createdAt", label: "التاريخ" },
    ],
  }),
  "system-settings": resource({
    key: "system-settings",
    title: "إعدادات النظام",
    description: "إعدادات عامة وقواعد KPI والرواتب.",
    delegate: "systemSetting",
    route: "/settings",
    api: "/api/system-settings",
    searchFields: ["key", "updatedBy"],
    columns: [
      { key: "key", label: "المفتاح" },
      { key: "updatedBy", label: "آخر تعديل بواسطة" },
      { key: "updatedAt", label: "آخر تحديث" },
    ],
  }),
  "vehicle-movements": resource({
    key: "vehicle-movements",
    title: "حركة السيارات",
    description: "تسليم واستلام ونقل السيارات وربطها بالمناديب.",
    delegate: "vehicleMovement",
    route: "/vehicle-movements",
    api: "/api/vehicle-movements",
    searchFields: ["vehicleId", "fromDriverId", "toDriverId", "movementType", "status", "notes"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "fromDriverId", label: "من مندوب" },
      { key: "toDriverId", label: "إلى مندوب" },
      { key: "movementType", label: "نوع الحركة" },
      { key: "handoverDate", label: "تاريخ التسليم" },
      { key: "returnDate", label: "تاريخ الاستلام" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vehicle-cleaning": resource({
    key: "vehicle-cleaning",
    title: "نظافة السيارات",
    description: "متابعة نظافة السيارات وتكلفتها.",
    delegate: "vehicleCleaning",
    route: "/vehicle-cleaning",
    api: "/api/vehicle-cleaning",
    searchFields: ["vehicleId", "driverId", "status", "notes"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "driverId", label: "المندوب" },
      { key: "cleanDate", label: "تاريخ النظافة" },
      { key: "cost", label: "التكلفة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vehicle-maintenance": resource({
    key: "vehicle-maintenance",
    title: "الصيانة",
    description: "صيانة السيارات والتكلفة والمورد.",
    delegate: "vehicleMaintenance",
    route: "/vehicle-maintenance",
    api: "/api/vehicle-maintenance",
    searchFields: ["vehicleId", "driverId", "type", "vendor", "status"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "type", label: "نوع الصيانة" },
      { key: "vendor", label: "الورشة" },
      { key: "cost", label: "التكلفة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vehicle-authorizations": resource({
    key: "vehicle-authorizations",
    title: "التفويضات",
    description: "تفويضات السيارات والمناديب.",
    delegate: "vehicleAuthorization",
    route: "/authorizations",
    api: "/api/vehicle-authorizations",
    searchFields: ["vehicleId", "driverId", "authNumber", "status"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "driverId", label: "المندوب" },
      { key: "authNumber", label: "رقم التفويض" },
      { key: "endDate", label: "تاريخ الانتهاء" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "rental-companies": resource({
    key: "rental-companies",
    title: "شركات التأجير",
    description: "إدارة شركات تأجير السيارات.",
    delegate: "rentalCompany",
    route: "/rental-companies",
    api: "/api/rental-companies",
    searchFields: ["name", "contact", "phone", "status"],
    columns: [
      { key: "name", label: "الشركة" },
      { key: "contact", label: "مسؤول التواصل" },
      { key: "phone", label: "الجوال" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vehicle-costs": resource({
    key: "vehicle-costs",
    title: "تكلفة السيارات",
    description: "تكاليف السيارات الشهرية.",
    delegate: "vehicleCost",
    route: "/vehicle-cost",
    api: "/api/vehicle-costs",
    searchFields: ["vehicleId", "month", "status"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "month", label: "الشهر" },
      { key: "rentCost", label: "الإيجار" },
      { key: "maintenanceCost", label: "الصيانة" },
      { key: "totalCost", label: "الإجمالي" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vehicle-accidents": resource({
    key: "vehicle-accidents",
    title: "حوادث السيارات",
    description: "حوادث السيارات وتكلفتها وربطها بالمندوب.",
    delegate: "vehicleAccident",
    route: "/vehicle-accidents",
    api: "/api/vehicle-accidents",
    searchFields: ["vehicleId", "driverId", "type", "status"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "driverId", label: "المندوب" },
      { key: "type", label: "نوع الحادث" },
      { key: "cost", label: "التكلفة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vehicle-damages": resource({
    key: "vehicle-damages",
    title: "تلفيات السيارات",
    description: "تلفيات السيارات والتكلفة النهائية.",
    delegate: "vehicleDamage",
    route: "/vehicle-damages",
    api: "/api/vehicle-damages",
    searchFields: ["vehicleId", "driverId", "type", "status"],
    columns: [
      { key: "vehicleId", label: "السيارة" },
      { key: "driverId", label: "المندوب" },
      { key: "type", label: "نوع التلف" },
      { key: "finalCost", label: "التكلفة النهائية" },
      { key: "status", label: "الحالة" },
    ],
  }),
  invoices: resource({
    key: "invoices",
    title: "الفواتير",
    description: "فواتير المشاريع والعملاء.",
    delegate: "invoice",
    route: "/invoices",
    api: "/api/invoices",
    searchFields: ["number", "client", "month", "status", "invoiceStatus"],
    columns: [
      { key: "number", label: "رقم الفاتورة" },
      { key: "client", label: "العميل" },
      { key: "month", label: "الشهر" },
      { key: "amount", label: "المبلغ" },
      { key: "status", label: "الحالة" },
    ],
  }),
  receivables: resource({
    key: "receivables",
    title: "المستحقات",
    description: "المبالغ المستحقة على العملاء.",
    delegate: "receivable",
    route: "/receivables",
    api: "/api/receivables",
    searchFields: ["client", "status", "notes"],
    columns: [
      { key: "client", label: "العميل" },
      { key: "amount", label: "المبلغ" },
      { key: "paidAmount", label: "المدفوع" },
      { key: "dueDate", label: "تاريخ الاستحقاق" },
      { key: "status", label: "الحالة" },
    ],
  }),
  payments: resource({
    key: "payments",
    title: "المدفوعات",
    description: "مدفوعات الموردين والرواتب والمصروفات.",
    delegate: "payment",
    route: "/payments",
    api: "/api/payments",
    searchFields: ["payee", "method", "referenceNo", "status"],
    columns: [
      { key: "payee", label: "المستفيد" },
      { key: "amount", label: "المبلغ" },
      { key: "method", label: "طريقة الدفع" },
      { key: "referenceNo", label: "رقم المرجع" },
      { key: "status", label: "الحالة" },
    ],
  }),
  expenses: resource({
    key: "expenses",
    title: "المصروفات",
    description: "مصروفات التشغيل العامة.",
    delegate: "expense",
    route: "/expenses",
    api: "/api/expenses",
    searchFields: ["type", "month", "status", "notes"],
    columns: [
      { key: "type", label: "النوع" },
      { key: "amount", label: "المبلغ" },
      { key: "month", label: "الشهر" },
      { key: "status", label: "الحالة" },
    ],
  }),
  revenues: resource({
    key: "revenues",
    title: "الإيرادات",
    description: "إيرادات المشاريع والتطبيقات.",
    delegate: "revenue",
    route: "/revenues",
    api: "/api/revenues",
    searchFields: ["source", "month", "status", "notes"],
    columns: [
      { key: "source", label: "المصدر" },
      { key: "amount", label: "المبلغ" },
      { key: "month", label: "الشهر" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "supplier-accounts": resource({
    key: "supplier-accounts",
    title: "حسابات الموردين",
    description: "أرصدة الموردين والمدفوعات.",
    delegate: "supplierAccount",
    route: "/supplier-accounts",
    api: "/api/supplier-accounts",
    searchFields: ["supplier", "status", "notes"],
    columns: [
      { key: "supplier", label: "المورد" },
      { key: "balance", label: "الرصيد" },
      { key: "dueDate", label: "تاريخ الاستحقاق" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "cashbox-entries": resource({
    key: "cashbox-entries",
    title: "العهدة والصندوق",
    description: "حركة العهدة والصندوق.",
    delegate: "cashboxEntry",
    route: "/custody-cashbox",
    api: "/api/cashbox-entries",
    searchFields: ["type", "responsible", "status", "notes"],
    columns: [
      { key: "type", label: "النوع" },
      { key: "amount", label: "المبلغ" },
      { key: "balance", label: "الرصيد" },
      { key: "responsible", label: "المسؤول" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "bank-accounts": resource({
    key: "bank-accounts",
    title: "الحسابات البنكية",
    description: "الحسابات البنكية والأرصدة.",
    delegate: "bankAccount",
    route: "/bank-accounts",
    api: "/api/bank-accounts",
    searchFields: ["bankName", "iban", "status"],
    columns: [
      { key: "bankName", label: "البنك" },
      { key: "iban", label: "IBAN" },
      { key: "balance", label: "الرصيد" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "vat-records": resource({
    key: "vat-records",
    title: "VAT",
    description: "ضريبة القيمة المضافة.",
    delegate: "vatRecord",
    route: "/vat",
    api: "/api/vat-records",
    searchFields: ["month", "status"],
    columns: [
      { key: "month", label: "الشهر" },
      { key: "salesVat", label: "ضريبة المبيعات" },
      { key: "purchaseVat", label: "ضريبة المشتريات" },
      { key: "netVat", label: "صافي الضريبة" },
    ],
  }),
  "profit-loss": resource({
    key: "profit-loss",
    title: "الأرباح والخسائر",
    description: "تحليل الإيرادات والمصروفات وصافي الربح.",
    delegate: "profitLossRecord",
    route: "/profit-loss",
    api: "/api/profit-loss",
    searchFields: ["month", "status"],
    columns: [
      { key: "month", label: "الشهر" },
      { key: "revenues", label: "الإيرادات" },
      { key: "expenses", label: "المصروفات" },
      { key: "payroll", label: "الرواتب" },
      { key: "netProfit", label: "صافي الربح" },
    ],
  }),
  "quality-audits": resource({
    key: "quality-audits",
    title: "الجودة والتدقيق",
    description: "مراجعة جودة البيانات والتقارير والمهام.",
    delegate: "qualityAuditRecord",
    route: "/quality-audit",
    api: "/api/quality-audits",
    searchFields: ["entityType", "entityId", "result", "status"],
    columns: [
      { key: "entityType", label: "الكيان" },
      { key: "entityId", label: "رقم السجل" },
      { key: "result", label: "النتيجة" },
      { key: "reviewedBy", label: "المراجع" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "report-templates": resource({
    key: "report-templates",
    title: "قوالب التقارير",
    description: "إدارة قوالب التقارير والتصدير.",
    delegate: "reportTemplate",
    route: "/report-templates",
    api: "/api/report-templates",
    searchFields: ["name", "reportType", "status"],
    columns: [
      { key: "name", label: "اسم القالب" },
      { key: "reportType", label: "نوع التقرير" },
      { key: "status", label: "الحالة" },
      { key: "updatedAt", label: "آخر تحديث" },
    ],
  }),
  "excel-mappings": resource({
    key: "excel-mappings",
    title: "ربط أعمدة Excel",
    description: "خرائط الأعمدة المستخدمة في الاستيراد.",
    delegate: "excelMapping",
    route: "/excel-column-mapping",
    api: "/api/excel-mappings",
    searchFields: ["name", "importType", "status"],
    columns: [
      { key: "name", label: "اسم القالب" },
      { key: "importType", label: "نوع الاستيراد" },
      { key: "status", label: "الحالة" },
      { key: "updatedAt", label: "آخر تحديث" },
    ],
  }),
  "api-integrations": resource({
    key: "api-integrations",
    title: "API Integrations",
    description: "حالة التكاملات الخارجية.",
    delegate: "apiIntegration",
    route: "/api-integrations",
    api: "/api/api-integrations",
    searchFields: ["name", "provider", "status"],
    columns: [
      { key: "name", label: "الاسم" },
      { key: "provider", label: "المزود" },
      { key: "lastSyncAt", label: "آخر مزامنة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "backup-records": resource({
    key: "backup-records",
    title: "Backup/Restore",
    description: "النسخ الاحتياطي والاستعادة.",
    delegate: "backupRecord",
    route: "/backup-restore",
    api: "/api/backup-records",
    searchFields: ["fileName", "type", "status", "createdBy"],
    columns: [
      { key: "fileName", label: "اسم الملف" },
      { key: "type", label: "النوع" },
      { key: "createdBy", label: "بواسطة" },
      { key: "status", label: "الحالة" },
    ],
  }),
  "data-cleaning-issues": resource({
    key: "data-cleaning-issues",
    title: "تنظيف البيانات",
    description: "مشاكل البيانات والتكرارات والروابط الناقصة.",
    delegate: "dataCleaningIssue",
    route: "/data-cleaning",
    api: "/api/data-cleaning-issues",
    searchFields: ["issueType", "entityType", "entityId", "severity", "status"],
    columns: [
      { key: "issueType", label: "نوع المشكلة" },
      { key: "entityType", label: "الكيان" },
      { key: "severity", label: "الشدة" },
      { key: "status", label: "الحالة" },
    ],
  }),
};

export function getResource(key: string) {
  return resources[key] ?? null;
}

export const tablePages = [
  resources.drivers,
  resources.supervisors,
  resources.cities,
  resources.projects,
  resources.vehicles,
  resources.applications,
  resources["daily-reports"],
];
