services:
  - type: web
    name: mohamed-shawki-erp
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: npx next start --port $PORT
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mohamed-shawki-erp-db
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_NAME
        value: MOHAMED SHAWKI ERP
      - key: UPLOAD_DIR
        value: public/uploads

databases:
  - name: mohamed-shawki-erp-db
    databaseName: mohamed_shawki_erp
    user: erp_user
    region: frankfurt
    plan: free
    ipAllowList: []
